### ISSUE TITLE
Works with X52 Pro too?

### ISSUE THREAD

**Issue by nemesyssoft** [Becat72/X52DisplayTool#5]
Not really an issue. I've been looking around of the last 20 minute to see if there was any way to add a comment or send a message to you, just couldn't find anything.

The description talks about the X52 but does that tool is known to work with the X52 Pro?

Thanks and sorry for the noise.

**Comment by webbasan** [comment]
Yep, it is meant to work with the X52 pro - that's what I'm actually using. 
The main difference between them (afaik) are the R/G-LEDs on the X52pro and some additional lights. Don't know about differences of the display, but in the current state of the tool it's left to the user what has to be shown (no fancy scrolling - no inherent assumptions of how many characters can be displayed...)

**Comment by Becat72** [comment]
Hi Nemesyssoft,

As webbasan says, it works with the pro version too. Mind you, there are still some minor bugs and I want to make some minor changes to the program but my time for projects like these is so limited.

I hope you enjoy the software and if you have questions please feel free to contact me. You can do that through the elite frontier forum board, my name there is becat72.

Kind regards,
Bert

**Comment by nemesyssoft** [comment]
Thanks.

Sorry had to create a ticket. Like I said, didn’t find any way to ask questions. Great job, guys!
